const data = {
  products: [
    {
      name: 'Nike Slim shirt',
      slug: 'Nike Slim shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim shirt',
      slug: 'Nike Slim shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim shirt',
      slug: 'Nike Slim shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim shirt',
      slug: 'Nike Slim shirt',
      category: 'Shirts',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality shirt',
    },
  ],
};

export default data;
